export const FETCHED_DATA = "cars.FETCHED_DATA";
export const REQUESTED_DATA = "cars.REQUESTED_DATA";
export const CHANGED_PAGE = "cars.CHANGED_PAGE";
export const CHANGED_LIMIT = "cars.CHANGED_LIMIT";
export const CHANGED_SORT = "cars.CHANGED_SORT";
export const FETCHED_AIRPORTS_PICKUP_DATA = "cars.FETCHED_AIRPORTS_PICKUP_DATA";
export const FETCHED_AIRPORTS_RETURN_DATA = "cars.FETCHED_AIRPORTS_RETURN_DATA";